
export const bookLib = [
    {
      id: 1,
      title: "Harry Potter & the Chamber of Secrets",
      author: "J. K. Rowling",
      coverImage: "https://m.media-amazon.com/images/I/51-qC6c1ppL.jpg",
      description: "In his second year at Hogwarts School of Witchcraft and Wizardry, Harry Potter returns to find the school plagued by mysterious attacks that leave students petrified. Strange whispers echo through the halls, and a chilling message appears: 'The Chamber of Secrets has been opened. Enemies of the heir, beware.' With the help of his friends Ron Weasley and Hermione Granger, Harry investigates the legend of the Chamber of Secrets, believed to be hidden within the school and home to a deadly monster. As danger escalates and suspicion falls on Harry himself, he uncovers secrets from the past—about the founders of Hogwarts, the heir of Slytherin, and a young Tom Riddle.",
      price: 20.89,
      category: "Fiction",
      rating: 4.9,
      popular: true,
    },
    {
      id: 2,
      title: "1984",
      author: "George Orwell",
      coverImage: "https://m.media-amazon.com/images/I/91pu0kFwsuL._SL1500_.jpg",
      description: "1984 is set in a bleak, totalitarian society ruled by The Party, led by the omnipresent figure Big Brother. Citizens are under constant surveillance, and even thinking against the Party—thoughtcrime—is punishable. \nThe story follows Winston Smith, a low-ranking member of the Party in Airstrip One (formerly Britain). Secretly rebellious, Winston begins to question the regime, falls in love with a woman named Julia, and seeks truth in a world built on lies. But in a system that controls not just behavior but thought, language, and history, rebellion comes at a terrible price.",
      price: 8.99,
      category: "Sci-Fi",
      rating: 4.6,
      popular: true,
    },
    {
      id: 3,
      title: "The Richest Man in Babylon",
      author: "George S. Clason",
      coverImage: "https://m.media-amazon.com/images/I/71VZub0QnLL._SL1500_.jpg",
      description: "In the early 1920s, George S. Clason wrote a collection of parables set in ancient Babylon that provided guidance on one’s financial well-being. These parables were distributed as pamphlets to U.S. banking and insurance customers and were so well-received by the public that in 1926, the parables were collected into one volume under the title of his most famous story, The Richest Man in Babylon.",
      price: 5.99,
      category: "Classic",
      rating: 4.7,
    },
    {
      id: 4,
      title: "The Great Gatsby",
      author: "F. Scott Fitzgerald",
      coverImage: "https://m.media-amazon.com/images/I/81Q6WkLhX4L.jpg",
      description: "Set in 1920s New York, The Great Gatsby follows Nick Carraway, a Yale graduate and World War I veteran, who moves to West Egg, Long Island. There he becomes fascinated by his mysterious and wealthy neighbor, Jay Gatsby, known for his extravagant parties and deep longing for Daisy Buchanan—Nick’s cousin and Gatsby’s lost love. \nAs Nick is drawn into Gatsby’s world of luxury, lies, and longing, he discovers the hollow core beneath the glittering surface of the American Dream. The novel explores themes of love, wealth, illusion, social class, and the pursuit of happiness in a rapidly changing society.",
      price: 9.99,
      category: "Classic",
      rating: 4,
      popular: true,
    },
    {
      id: 5,
      title: "Moby Dick",
      author: "Herman Melville",
      coverImage: "https://m.media-amazon.com/images/I/71V+TBNTPCL._SL1491_.jpg",
      description: "Moby-Dick is the epic tale of Captain Ahab, a monomaniacal sea captain obsessed with seeking revenge on Moby Dick, a massive and elusive white sperm whale that once maimed him. The story is narrated by Ishmael, a thoughtful sailor who joins the whaling ship Pequod. As they journey across the oceans, the crew encounters philosophical questions, harrowing dangers, and the destructive power of obsession. A powerful exploration of human ambition, fate, and nature, Moby-Dick blends action, rich symbolism, and deep introspection. It's considered one of the greatest works of American literature.",
      price: 11.50,
      category: "Adventure",
      rating: 4.3,
    },
    {
      id: 6,
      title: "The Catcher in the Rye",
      author: "J.D. Salinger",
      coverImage: "https://m.media-amazon.com/images/I/81OthjkJBuL.jpg",
      description: "The Catcher in the Rye follows Holden Caulfield, a 16-year-old boy recently expelled from prep school, as he wanders through New York City over a few days. Disillusioned by the 'phoniness' of the adult world, Holden struggles with feelings of isolation, confusion, and loss. Told in Holden’s distinctive, sarcastic, and emotionally raw voice, the novel explores themes of identity, alienation, adolescence, and the painful process of growing up. Holden dreams of being the “catcher in the rye,” saving children from losing their innocence.",
      price: 7.99,
      category: "Fiction",
      rating: 3.9,
    },
    {
      id: 7,
      title: "Brave New World",
      author: "Aldous Huxley",
      coverImage: "https://m.media-amazon.com/images/I/91D4YvdC0dL.jpg",
      description: "Brave New World is set in a futuristic society where human beings are genetically engineered, mass-produced, and conditioned for their roles in a strictly controlled, pleasure-driven world. Individuality, family, and emotional depth are sacrificed for the sake of social stability and consumer happiness.The story follows Bernard Marx, an outsider in this utopian society, and John 'the Savage', a man born outside the system who challenges its values when he is brought into the modern world. Through their experiences, Huxley explores themes of freedom, identity, technology, conformity, and the cost of sacrificing humanity for comfort.",
      price: 12.99,
      category: "Sci-Fi",
      rating: 4.6,
    },
    {
      id: 8,
      title: "Frankenstein the Original 1818",
      author: "Mary Shelley ",
      coverImage: "https://m.media-amazon.com/images/I/51BP3ObL3UL._SL1360_.jpg",
      description: "Young scientist Victor Frankenstein, grief-stricken over the death of his mother, sets out in a series of laboratory experiments testing the ability to create life from non-living matter. Soon, his experiments progress further until he creates a humanoid creature eight feet tall. But as Frankenstein soon discovers, a successful experiment does not always equal a positive outcome.",
      price: 15.99,
      category: "Classic",
      rating: 4.5,
    },
    {
      id: 9,
      title: "Crime and Punishment",
      author: "Fyodor Dostoevsky",
      coverImage: "https://m.media-amazon.com/images/I/51Vg24nKbPL._SL1200_.jpg",
      description: "Crime and Punishment follows Rodion Raskolnikov, a poor and conflicted former student in St. Petersburg, Russia, who believes he is intellectually and morally justified in murdering a corrupt pawnbroker for the greater good. After committing the crime, he is plagued by guilt, paranoia, and inner torment, as he struggles to reconcile his actions with his conscience. The novel explores deep themes such as morality, justice, redemption, alienation, and the psychology of crime. Through Raskolnikov’s psychological breakdown and eventual search for redemption, Dostoevsky questions the nature of evil and whether true repentance can lead to salvation.",
      price: 9.50,
      category: "Classic",
      rating: 3.6,
    },
    {
      id: 10,
      title: "The Hobbit",
      author: "J.R.R. Tolkien",
      coverImage: "https://m.media-amazon.com/images/I/712cDO7d73L._SL1500_.jpg",
      description: "The Hobbit follows the journey of Bilbo Baggins, a quiet and unadventurous hobbit who lives in the peaceful land of the Shire. His life changes when the wizard Gandalf and a group of thirteen dwarves recruit him to join a quest to reclaim the dwarves' lost kingdom and treasure from Smaug, a fearsome dragon. Reluctantly drawn into an epic adventure, Bilbo encounters trolls, goblins, elves, giant spiders, and Gollum, from whom he obtains the mysterious One Ring. As the journey unfolds, Bilbo discovers courage, cleverness, and strength he never knew he had.",
      price: 13.99,
      category: "Fantasy",
      rating: 4.8,
    },
    {
      id: 11,
      title: "The Road",
      author: "Cormac McCarthy",
      coverImage: "https://m.media-amazon.com/images/I/51M7XGLQTBL._AC_UF1000,1000_QL80_.jpg",
      description: "The Road tells the bleak yet deeply emotional story of a father and his young son journeying across a burned, desolate America after an unnamed catastrophe. With no clear destination and little hope, they travel through ash-covered landscapes, scavenging for food and avoiding violent survivors, guided only by their love for each other and a shared will to survive. Told in spare, poetic prose, the novel explores themes of parenthood, survival, morality, and the enduring bond between parent and child. Despite its darkness, The Road carries a quiet beauty and hope, symbolized by the father's insistence that they are 'carrying the fire.'",
      price: 10.50,
      category: "Literature",
      rating: 3.4,
    },
    {
      id: 12,
      title: "The Kite Runner",
      author: "Khaled Hosseini",
      coverImage: "https://m.media-amazon.com/images/I/81IzbD2IiIL._AC_UF1000,1000_QL80_.jpg",
      description: "The Kite Runner follows the story of Amir, a privileged boy from Kabul, Afghanistan, and his loyal friend and servant’s son, Hassan. Set against the backdrop of Afghanistan's political turmoil—from the fall of the monarchy to the rise of the Taliban—the novel explores how one moment of betrayal in their childhood haunts Amir into adulthood. Years later, Amir, now living in the U.S., is called back to a very different Afghanistan to confront his past and seek redemption. The novel explores themes of guilt, friendship, betrayal, class, and the possibility of forgiveness.",
      price: 8.99,
      category: "Adventure",
      rating: 4.7,
    },
    {
      id: 13,
      title: "A Game of Thrones (Song of Ice and Fire)",
      author: "George R. R. Martin",
      coverImage: "https://m.media-amazon.com/images/I/71Jzezm8CBL._SL1200_.jpg",
      description: "Winter is coming. Such is the stern motto of House Stark, the northernmost of the fiefdoms that owe allegiance to King Robert Baratheon in far-off King’s Landing. There Eddard Stark of Winterfell rules in Robert’s name. There his family dwells in peace and comfort: his proud wife, Catelyn; his sons Robb, Brandon, and Rickon; his daughters Sansa and Arya; and his bastard son, Jon Snow. Far to the north, behind the towering Wall, lie savage Wildings and worse—unnatural things relegated to myth during the centuries-long summer, but proving all too real and all too deadly in the turning of the season.",
      price: 16.44,
      category: "Fantasy",
      rating: 4.8,
    },
    {
      id: 14,
      title: "Life of Pi",
      author: "Yann Martel",
      coverImage: "https://m.media-amazon.com/images/I/719OJrcrB-L._SL1500_.jpg",
      description: "Life of Pi tells the extraordinary story of Piscine Molitor Patel (nicknamed Pi), a teenage boy from India with a deep interest in religion and zoology. After his family decides to emigrate to Canada, their ship sinks in the Pacific Ocean—leaving Pi stranded on a lifeboat with an unexpected companion: a Bengal tiger named Richard Parker. As they drift for 227 days, Pi must use his knowledge, faith, and willpower to survive the vast ocean, harsh weather, and the presence of a wild animal. The novel blends spiritual reflection, imaginative storytelling, and questions about truth and belief.",
      price: 9.99,
      category: "Adventure",
      rating: 4.6,
      popular: true,
    },
    {
      id: 15,
      title: "The Handmaid's Tale",
      author: "Margaret Atwood",
      coverImage: "https://m.media-amazon.com/images/I/61su39k8NUL._AC_UF1000,1000_QL80_.jpg",
      description: "Set in the near-future totalitarian regime of Gilead, The Handmaid’s Tale follows Offred, a woman forced to serve as a Handmaid—a concubine assigned to elite men to bear children in a society plagued by infertility. Under a harsh religious dictatorship, women are stripped of their rights, identities, and autonomy. Offred lives in fear but clings to memories of her past, her lost family, and small acts of resistance. Through her voice, Atwood explores themes of power, gender oppression, religious extremism, identity, and the fight for freedom.",
      price: 10.99,
      category: "Literature",
      rating: 4.5,
    },
    {
      id: 16,
      title: "Napoleon: A Life",
      author: "Andrew Roberts",
      coverImage: "https://m.media-amazon.com/images/I/91t3V3rQsUL._SL1500_.jpg",
      description: "In Napoleon: A Life, historian Andrew Roberts presents a richly detailed and balanced portrait of Napoleon Bonaparte—the ambitious Corsican who rose to become Emperor of France and reshaped Europe through his military genius and reforms. Drawing from a vast range of sources, including Napoleon’s 33,000 letters, Roberts offers deep insight into Napoleon’s mind, motivations, and legacy. The biography explores his military campaigns, political strategies, personal relationships, and the enduring impact of his rule on France and the modern world.",
      price: 13.53,
      category: "Biography",
      rating: 4.6,
    },
    {
      id: 17,
      title: "Fahrenheit 451",
      author: "Ray Bradbury",
      coverImage: "https://m.media-amazon.com/images/I/61l8LHt4MeL._AC_UF1000,1000_QL80_.jpg",
      description: "Set in a future society where books are banned and “firemen” burn any that are found, Fahrenheit 451 follows Guy Montag, a fireman who begins to question the world around him. Once a loyal servant of the oppressive regime, Montag becomes disillusioned after meeting a free-spirited young woman named Clarisse and witnessing the suicide of a woman who chooses to die with her books. As Montag secretly begins to read and think for himself, he becomes a target of the very system he once served. The novel explores themes of censorship, knowledge vs. ignorance, government control, and the importance of critical thinking and literature.",
      price: 8.50,
      category: "Sci-Fi",
      rating: 4.3,
    },
    {
      id: 18,
      title: "Wings of Fire: An Autobiography",
      author: "Abdul A.P.J. Kalam, Arun Tiwari",
      coverImage: "https://m.media-amazon.com/images/I/61MR-YfM4CL._SL1400_.jpg",
      description: "Wings of Fire traces the remarkable journey of Avul Pakir Jainulabdeen Abdul Kalam, from his humble beginnings in the small town of Rameswaram, Tamil Nadu, to becoming one of India’s most celebrated aerospace scientists and eventually the 11th President of India.Born to a poor boat-owner, Kalam’s early life was shaped by simplicity, discipline, and strong values. The book chronicles his education, his work at ISRO and DRDO, and his pivotal role in developing India's satellite launch vehicles and ballistic missile programs—earning him the nickname “Missile Man of India.”",
      price: 25.16,
      category: "Biography",
      rating: 4.3,
      popular: true,
    },
    {
      id: 19,
      title: "The Alchemist",
      author: "Paulo Coelho",
      coverImage: "https://m.media-amazon.com/images/I/61HAE8zahLL._AC_UF1000,1000_QL80_.jpg",
      description: "The Alchemist tells the story of Santiago, a young Andalusian shepherd boy who dreams of discovering a hidden treasure near the Egyptian pyramids. He sets off on a journey across the desert in search of his 'Personal Legend'—his true purpose in life. Along the way, Santiago meets a series of mentors, including a mysterious alchemist, who teach him spiritual and practical lessons about listening to his heart, reading the signs of the universe, and trusting the journey. Through trials and discoveries, Santiago learns that true treasure lies not in gold, but in self-discovery and inner transformation.",
      price: 10.99,
      category: "Fiction",
      rating: 4.6,
    },
    {
      id: 20,
      title: "The Chronicles of Narnia: The Lion, the Witch and the Wardrobe",
      author: "C.S. Lewis",
      coverImage: "https://m.media-amazon.com/images/I/81N3dK1fIIL._SL1500_.jpg",
      description: `During World War II, four siblings—Peter, Susan, Edmund, and Lucy Pevensie—are sent to the English countryside for safety. In the mysterious old house where they’re staying, Lucy discovers a magical wardrobe that leads to the world of Narnia, a land frozen in eternal winter under the rule of the evil White Witch. 
      As the children explore Narnia, they become part of a great prophecy and join forces with Aslan, a noble and powerful lion, to free the land from the witch’s tyranny. Through betrayal, sacrifice, and courage, the children come of age and help restore peace to Narnia.`,
      price: 7.99,
      category: "Fantasy",
      rating: 4.8,
      popular: true,
    },
    {
      id: 21,
      title: "kigai: Japanese secret to long and happy life",
      author: "Francesc García, Héctor,Miralles",
      coverImage: "https://m.media-amazon.com/images/I/81l3rZK4lnL._SL1500_.jpg",
      description: "Ikigai (生き甲斐) is a Japanese concept that means “a reason for being”—the thing that gives your life meaning and motivates you to get out of bed each morning. This book explores how finding your ikigai can lead to greater happiness, better health, and even longevity. The authors travel to Okinawa, Japan, home to one of the world’s highest concentrations of centenarians, to uncover the lifestyle secrets of its remarkably long-lived people. They combine interviews, cultural insights, and scientific research to show how purpose, community, simplicity, diet, and a sense of flow contribute to a fulfilling life.",
      price: 9.30,
      category: "Non-Fiction",
      rating: 4.6,
      popular: true,
    },
    {
      id: 22,
      title: "The Psychology of Money",
      author: "Morgan Housel",
      coverImage: "https://m.media-amazon.com/images/I/715ucF1cMZS._SL1500_.jpg",
      description: "It's about how you behave. And behavior is hard to teach, even to really smart people. How to manage money, invest it, and make business decisions are typically considered to involve a lot of mathematical calculations, where data and formulae tell us exactly what to do. But in the real world, people don't make financial decisions on a spreadsheet.",
      price: 6.20,
      category: "Non-Fiction",
      rating: 4.6,
    },
    {
      id: 23,
      title: "The Power of Your Subconscious Mind",
      author: "Joseph Murphy",
      coverImage: "https://m.media-amazon.com/images/I/61QipPhOo4L._SL1491_.jpg",
      description: "In The Power of Your Subconscious Mind Dr. Joseph Murphy gives you the tools you will need to unlock the awesome powers of your subconscious mind. You can improve your relationships your finances your physical well-being. Once you learn how to use this unbelievably powerful force there is nothing you will not be able to accomplish. Join the millions of people who have already unlocked the power of their subconscious minds.",
      price: 16.99,
      category: "Non-Fiction",
      rating: 4.6,
    },
    {
      id: 24,
      title: "Atomic Habits",
      author: "James Clear",
      coverImage: "https://m.media-amazon.com/images/I/81ANaVZk5LL._SL1500_.jpg",
      description: "No matter your goals, Atomic Habits offers a proven framework for improving--every day. James Clear, one of the world's leading experts on habit formation, reveals practical strategies that will teach you exactly how to form good habits, break bad ones, and master the tiny behaviors that lead to remarkable results.",
      price: 14.20,
      category: "Non-Fiction",
      rating: 4.8,
    },
    {
      id: 25,
      title: "Strangers in Time",
      author: "David Baldacci",
      coverImage: "https://m.media-amazon.com/images/I/816QI0pfuRL._SL1500_.jpg",
      description: "Fourteen-year-old Charlie Matters is up to no good, but for a very good reason. Without parents, peerage, or merit, he steals what he needs, living day-to-day until he’s old enough to enlist to fight the Germans. After barely surviving the Blitz, Charlie knows there’s no telling when a falling bomb might end his life. ",
      price: 17.84,
      category: "Fiction",
      rating: 4.5,
    },
    {
      id: 26,
      title: "Silent Retreat",
      author: "Sally Quinn",
      coverImage: "https://m.media-amazon.com/images/I/81-TV1yoMOL._SL1500_.jpg",
      description: "When prize-winning reporter Sybilla Sumner checks into a monastery for a silent retreat, romance is the last thing on her mind. She plans to spend five meditative days surrounded by the beauty of the Shenandoah Valley—and apart from her famous husband and their crumbling marriage.",
      price: 28.00,
      category: "Fiction",
      rating: 3.9,
    },
    {
      id: 27,
      title: "The Midnight Library",
      author: "Matt Haig",
      coverImage: "https://m.media-amazon.com/images/I/71ls-I6A5KL._SL1500_.jpg",
      description: "Somewhere out beyond the edge of the universe there is a library that contains an infinite number of books, each one the story of another reality. One tells the story of your life as it is, along with another book for the other life you could have lived if you had made a different choice at any point in your life.",
      price: 9.54,
      category: "Sci-Fi",
      rating: 4.4,
    },
    {
      id: 28,
      title: "The Wager: A Tale of Shipwreck, Mutiny and Murder",
      author: "David Grann",
      coverImage: "https://m.media-amazon.com/images/I/91lUa7PChXL._SL1500_.jpg",
      description: "The Wager is a grand tale of human behavior at the extremes told by one of our greatest nonfiction writers. Grann’s recreation of the hidden world on a British warship rivals the work of Patrick O’Brian, his portrayal of the castaways’ desperate straits stands up to the classics of survival writing such as The Endurance, and his account of the court martial has the savvy of a Scott Turow thriller.",
      price: 2.92,
      category: "Adventure",
      rating: 4.4,
    },
    {
      id: 29,
      title: "Curse of Shadows and Thorns",
      author: "Lj Andrews",
      coverImage: "https://m.media-amazon.com/images/I/71ctswHqbIL._SL1360_.jpg",
      description: "A rebellious princess. A cursed rogue. A forbidden love that will bring a kingdom to its knees. Filled with luscious world building, banter-filled romance, and epic battles, this first book in the dark, fantasy romance series, The Broken Kingdoms, part Viking, part fairy tale. One-click to start reading today.",
      price: 26.96,
      category: "Fantasy",
      rating: 4.4,
    },
    {
      id: 30,
      title: "Trust (Pulitzer Prize Winner)",
      author: "Hernan Diaz",
      coverImage: "https://m.media-amazon.com/images/I/81OSqvrGtlL._SL1500_.jpg",
      description: "Hernan Diaz’s TRUST elegantly puts these competing narratives into conversation with one another—and in tension with the perspective of one woman bent on disentangling fact from fiction. The result is a novel that spans over a century and becomes more exhilarating with each new revelation.",
      price: 13.91,
      category: "Literature",
      rating: 4.1,
      popular: true,
    },
    {
      id: 31,
      title: "The Secret Life Of Sunflowers",
      author: "Marta Molnar",
      coverImage: "https://m.media-amazon.com/images/I/81aTiUFnLrL._SL1360_.jpg",
      description: "When Hollywood auctioneer Emsley Wilson finds her famous grandmother's diary while cleaning out her New York brownstone, the pages are full of surprises. The first surprise is, the diary isn't her grandmother's. It belongs to Johanna Bonger, Vincent van Gogh's sister-in-law.",
      price: 21.99,
      category: "Biography",
      rating: 4.3,
    },
    {
      id: 32,
      title: "The Lost Bookshop",
      author: "Evie Woods",
      coverImage: "https://m.media-amazon.com/images/I/91Sy3S-198L._SL1500_.jpg",
      description: "The Lost Bookshop is an ode to bibliophiles: a beautifully wrought tale about the magic of stories, the bonds we craft, and the courage to reclaim one’s voice. While its ambitious structure may not please every reader, its emotional resonance and literary charm have captured the hearts of many.",
      price: 7.99,
      category: "Literature",
      rating: 4.4,
    },
    {
      id: 33,
      title: "Steve Jobs",
      author: "Walter Isaacson",
      coverImage: "https://m.media-amazon.com/images/I/81nRXuesUkL._SL1500_.jpg",
      description: "Steve Jobs by Walter Isaacson is the definitive biography of one of the most iconic innovators of the 20th and early 21st centuries. Based on over 40 interviews with Jobs himself over two years—and hundreds more with family, friends, colleagues, competitors, and adversaries—this book offers a rare, honest, and complex portrait of a man who transformed entire industries. Isaacson traces Jobs’s life from his adoption and childhood in California, through the founding of Apple in his parents’ garage, to his time at Pixar, and his return to Apple, where he led a renaissance of innovation with products like the iMac, iPod, iPhone, and iPad.",
      price: 25.11,
      category: "Biography",
      rating: 4.6,
    },
  ];

export const categories = ["All", "Fiction", "Classic", "Adventure", "Non-Fiction", "Sci-Fi", "Literature", "Fantasy", "Biography"];
